# Generated by Django 5.0.6 on 2024-07-08 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_order_checkout_customer_checkout_date_added_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='name',
            new_name='username',
        ),
    ]
