# Generated by Django 5.0.6 on 2024-07-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_checkout_customer_alter_order_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
