# Generated by Django 5.0.6 on 2024-07-08 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_alter_order_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='customer',
            new_name='registration',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.AddField(
            model_name='order',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.registration'),
        ),
    ]
