# Generated by Django 5.0.6 on 2024-07-08 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_rename_user_checkout_customer_remove_order_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='customer',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='user',
        ),
    ]
