# Generated by Django 4.2.6 on 2024-07-12 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_alter_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='items_json',
        ),
    ]
