# Generated by Django 5.0.6 on 2024-07-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='order_id',
        ),
        migrations.AddField(
            model_name='checkout',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
