# Generated by Django 5.0.6 on 2024-07-12 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_delete_registration_remove_checkout_order_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blogpost',
        ),
    ]
