# Generated by Django 5.0.6 on 2024-07-12 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_delete_blogpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderUpdate',
        ),
    ]
