# Generated by Django 5.0.6 on 2024-07-12 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_checkout_amount_checkout_final_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='final_order',
        ),
    ]
