# Generated by Django 5.0.6 on 2024-07-12 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_remove_checkout_amount_remove_checkout_final_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='checkout',
            name='final_order',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
