# Generated by Django 5.0.6 on 2024-07-12 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_checkout_amount_checkout_final_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
