# Generated by Django 4.2.6 on 2024-07-13 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_delete_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
