# Generated by Django 4.2.11 on 2025-01-08 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_alter_checkout_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iteminsert',
            name='item_date',
        ),
    ]
